version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - fleet-management-net
  fleet-management-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: fleet-management-kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://fleet-management-kafka:9092,PLAINTEXT_HOST://fleet-management-kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - fleet-management-kafka-volume:/var/lib/kafka/data
    networks:
      - fleet-management-net
  fleet-management-mysql:
    image: mysql:8.0
    volumes:
      - fleet-management-mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=FLEET_MANAGEMENT
      - MYSQL_USER=FLEET-MANAGEMENT-USER
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    networks:
      - fleet-management-net
  fleet-management-mongo-db:
    image: "mongo:4.4.3"
    restart: always
    volumes:
      - fleet-management-mongo-db-volume:/data/db
    ports:
      - 27017:27017
    networks:
      - fleet-management-net
  feet-management-app:
    image: fleet-management-image:latest
    restart: on-failure
    depends_on:
      - fleet-management-kafka
      - fleet-management-mongo-db
      - fleet-management-mysql
    ports:
      - 8080:8080
    networks:
      - fleet-management-net

volumes:
  fleet-management-mysql-volume:
  fleet-management-mongo-db-volume:
  fleet-management-kafka-volume:

networks:
  fleet-management-net:
    driver: bridge