spring:
  kafka:
    consumer:
      group-id: fleet-management-log
      auto-offset-reset: latest
    bootstrap-servers: fleet-management-kafka:29092
    topic:
      name: fleet-log
  application:
    name: Fleet-Management
  flyway:
    schemas: FLEET_MANAGEMENT
    user: root
    password: root
    url: jdbc:mysql://fleet-management-mysql:3306/mysql
    enabled: true
  data:
    mongodb:
      port: '27017'
      host: fleet-management-mongo-db
      database: fleet_management
  jpa:
    defer-datasource-initialization: 'false'
    show-sql: 'true'
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    password: password
    username: FLEET-MANAGEMENT-USER
    url: jdbc:mysql://fleet-management-mysql:3306/FLEET_MANAGEMENT?useSSL=false&allowPublicKeyRetrieval=true
management:
  server:
    port: '8081'
  health:
    circuitbreakers:
      enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: '8080'

resilience4j.circuitbreaker:
  instances:
    myProjectAllRemoteCallsCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
      permittedNumberOfCallsInHalfOpenState: 4
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 5s
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 10
      failureRateThreshold: 50